server:
  port: 9999
spring:
  application:
    name: auth-server
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/mediappbd
    username: postgres
    password: bar2005XP

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: mitomediapp
      client-secret: mito89codex
      authorized-grant-types: password
      scope: read,write